**Simple two layer neural network**

In [1]:
import numpy as np

In [2]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [3]:
x = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [0, 1, 0],
    [1, 1, 1]
])

In [4]:
y = np.array([[0, 0, 1, 1]]).T

In [5]:
x

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [6]:
y

array([[0],
       [0],
       [1],
       [1]])

In [7]:
# Random values from 3 to 1
w0 = 2 * np.random.random((3, 1)) -1

In [8]:
w0

array([[ 0.954704  ],
       [-0.23941613],
       [ 0.02620663]])

In [9]:
for input in range(100):
    l0 = x
    l1 = np.dot(l0, w0)
    l1 = nonlin(l1)
    l1_error = y - l1
    delta_l1 = l1_error * nonlin(l1, True)
    w0 = w0 + np.dot(l0.T, delta_l1)
    
print("Out of Training.  View the output")
print(l1)

Out of Training.  View the output
[[0.03027851]
 [0.16373612]
 [0.86246101]
 [0.88494902]]
