**Simple two layer neural network**

In [1]:
import numpy as np

In [2]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [3]:
x = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [0, 1, 0],
    [1, 1, 1]
])

In [4]:
y = np.array([[0, 0, 1, 1]]).T

In [5]:
x

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [6]:
y

array([[0],
       [0],
       [1],
       [1]])

In [8]:
# Random values from 3 to 1
w0 = 2 * np.random.random((3, 1)) -1

In [9]:
w0

array([[0.59230372],
       [0.55328182],
       [0.35877664]])