**Simple two layer neural network**

In [1]:
import numpy as np

In [2]:
#sigmoid function
def nonlin(x, deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1 + np.exp(-x))

In [3]:
x = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [0, 1, 0],
    [1, 1, 1]
])

In [4]:
y = np.array([[0, 0, 1, 1]]).T

In [5]:
x

array([[0, 0, 1],
       [0, 1, 1],
       [0, 1, 0],
       [1, 1, 1]])

In [6]:
y

array([[0],
       [0],
       [1],
       [1]])

In [8]:
# Random values from 3 to 1
w0 = 2 * np.random.random((3, 1)) -1

In [9]:
w0

array([[0.59230372],
       [0.55328182],
       [0.35877664]])

In [10]:
for input in range(10):
    l0 = x
    l1 = np.dot(l0, w0)
    l1 = nonlin(l1)
    l1_error = y - l1
    delta_l1 = l1_error * nonlin(l1, True)
    w0 = w0 + np.dot(l0.T, delta_l1)
    
print("Out of Training.  View the output")
print(l1)

Out of Training.  View the output
[[0.25493621]
 [0.41167684]
 [0.67159741]
 [0.6837249 ]]
